crontask: '0 0 4 * * *' # 默认的这个表达式表示每天凌晨4:00备份
# 表达式格式为Cron

# Cron表达式简易教程如下
# * * * * * *
# | | | | | |
# | | | | | +---- 星期几          (1-7)
# | | | | +------ 月份            (1-12)
# | | | +-------- 每月的第几天    (1-31)
# | | +---------- 小时            (0-23)
# | +------------ 分钟            (0-59)
# +-------------- 秒钟            (0-59)

# 如果不懂可以使用Cron生成器：https://github.com/eagle3236/Cron-GUI/blob/master/README.md

backup-format: 'eBackup {DATE}' #备份文件名字

# 存储备份的文件夹
backup-path: 'plugins/eBackup/backups'

# 备份数量阈值，检测到备份文件多于这个数量时会删除旧备份。 (设置为0可禁用此功能)
# 如果开启FTP/SFTP备份则此项无效。
max-backups: 20

# FTP/SFTP设定
# 如果开启此功能，上面的 max-backups 将失效。
ftp:
    enable: false
    type: sftp # 可设为ftp或sftp
    host: 'localhost'
    port: 22
    user: 'username'
    pass: 'password'
    path: '~/backups/'

# 你要备份什么文件？
# 默认会备份整个服务器文件夹。你可以在此处设置无需备份的内容。
backup:
    pluginjars: false # JAR后缀的插件
    pluginconfs: false # 所有插件的数据
    ignore: # *不*备份的文件夹
        - 'plugins/eBackup/backups' # 如果使用本地备份，请不要删除这一行
        - 'plugins/dynmap' #卫星地图文件夹（如果有）
        - 'logs' #日志文件夹
        - 'cache' #缓存文件夹